### ISSUE TITLE
Keyed json?

### ISSUE THREAD

**Issue by TMcLoone** [johnturingan/gulp-advanced-csv-to-json#3]
Hey really cool project!! 
Is there any way to get keyed json like you can do here - https://www.convertcsv.com/csv-to-json.htm i.e. grouping all rows by one column first?

**Comment by johnturingan** [comment]
Hey Thanks @TMcLoone 
Sorry but can you send me like a sample CSV and expected result? Then i'll try to include the feature. Or if you can make a pull request that would also be nice. Thanks

**Comment by TMcLoone** [comment]
Couldn't place the file here but you can get it from my drobox:
https://www.dropbox.com/s/904accpadfirjra/csv_example.csv?dl=0

Output would be this:

`{
   "Male": [
      {
         "Weight": 90,
         "Location": "London",
         "Name": "John"
      },
      {
         "Weight": 120,
         "Location": "London",
         "Name": "James"
      },
      {
         "Weight": 65,
         "Location": "London",
         "Name": "Jamie"
      },
      {
         "Weight": 75,
         "Location": "London",
         "Name": "Jamie"
      }
   ],
   "Female": [
      {
         "Weight": 110,
         "Location": "London",
         "Name": "Jamie"
      },
      {
         "Weight": 90,
         "Location": "London",
         "Name": "Jamie"
      },
      {
         "Weight": 56,
         "Location": "London",
         "Name": "Jamie"
      },
      {
         "Weight": 56,
         "Location": "London",
         "Name": "Jamie"
      },
      {
         "Weight": 80,
         "Location": "London",
         "Name": "Jamie"
      }
   ]
}`

**Comment by johnturingan** [comment]
@TMcLoone I publish a new version, Hope that will help you. Thanks. Closing this now

**Comment by TMcLoone** [comment]
Awesome thank you!! Can I buy you a coffee/beer?

**Comment by johnturingan** [comment]
All good man! Thank you! Always happy to help ;)
